### ISSUE TITLE
ability to search on different Ranges than the ones already available

### ISSUE THREAD

**Issue by drPeidos** [TrinTragula/seeder#11]
Right now the maximum range is 1k blocks. It would be nice to have bigger ranges, or even nicer would be to have customs ranges. A warning could be given to the user that selects ranges bigger than 1k blocks, saying something like "searching on ranges bigger than 1k blocks takes more time, please be patient".
Thanks.

**Comment by TrinTragula** [comment]
This feature is now live (version 0.4.4). 
You should be able to select a custom range using "advanced mode":


![immagine](https://user-images.githubusercontent.com/21279788/231523917-82c0f19f-0ec8-4966-8a7a-d877ae137650.png)


Thanks for the feedback!

**Comment by drPeidos** [comment]
Nice. Thank you :)
