### ISSUE TITLE
[Help/Bug] Website page not loading correctly

### ISSUE THREAD

**Issue by RandomGgames** [TrinTragula/seeder#23]
Context: I've been to this website on my PC before. I have no idea what I've changed since, but chrome, incognito chrome, and edge all load the page like this:
![image](https://github.com/TrinTragula/seeder/assets/17207260/54668303-b0dd-43f2-87e8-96741c2cb284)

It works fine on my laptop though, but I haven't noticed an issue with any other website, so I'm not sure what's up.
Changing zoom does not work, restart does not work, clearing history/resetting chrome settings does not work.

**Comment by MaddMelii** [comment]
I am having the exact same issue and i'm not sure why..

**Comment by Maks7594** [comment]
This also happens on Arc Browser
![image](https://github.com/TrinTragula/seeder/assets/72873506/0a287dac-71a8-413f-b4a2-f435e2ec3633)

**Comment by Egamer25** [comment]
I have this issue and I can kinda fix it by inspecting the style sheet and changing a width setting to like 600 but it reverts on next reload, I am guessing the stylesheet Is messed up somehow so its not scaling properly.

**Comment by TrinTragula** [comment]
I deployed a fixed version, let me know if the problem persists. And thanks for the feedback!
