### ISSUE TITLE
Feature: Find seeds with spawn in biome/x distance from 0, 0

### ISSUE THREAD

**Issue by CEbbinghaus** [TrinTragula/seeder#5]
It would be awesome to be able to more narrowly search for seeds that have the spawn set either in a particular biome (only possible if that biome is surrounded by enough water to stop the spawn wandering. Or to just say that the spawn has to be at most x blocks away from 0, 0 allowing for very similar behavior.

I'm trying to find a Seed that has the player spawning on a mushroom island which is quite rare and therefore requires a lot more searching. Manually clicking the regenerate button, again and again, is much too slow to give any kind of results.

Thanks for such a awesome tool

**Comment by TrinTragula** [comment]
Hi! Thank you so much for your interest, but I guess I should add why I'm currently not developing this feature.
Guessing the right spawn is a very CPU intensive process that, as far as I know, can't be done while searching for biomes that match a given criteria. For this reason the app just shows you spawn after finding a given seed.
I sadly don't see this feature being added in the near future, but maybe something will change!

I'll re-open this issue if this will ever be the case.
