### ISSUE TITLE
Add a timer to the seed search feature

### ISSUE THREAD

**Issue by TH3N3WN00B** [TrinTragula/seeder#8]
Add a timer / clock to the seed finder screen maybe between the seed amount per second and the ''stop'' button

![image](https://user-images.githubusercontent.com/10799738/226092579-3f05582f-281b-46c9-9578-d73dc3beb284.png)

it has been going on like this for like 2 hours now.... have I broken the site?

**Comment by TH3N3WN00B** [comment]
Yes, a time telling me how much time has passed since the search started

**Comment by TrinTragula** [comment]
This feature is now live (version 0.4.4). Thanks for the feedback!
